use_frameworks!

platform :ios, '8.0'

target 'WGImageTool_Example' do
  pod 'WGImageTool', :path => '../'

  target 'WGImageTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
